### ISSUE TITLE
Can't use mouse 

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#69] opened 2018-05-01 22:04 UTC
Efficiency issue: Observation box function example: start typing in the observation name and you get 7 choices that are close to what you want. We used to be able to use the mouse to select the one you want. If you use the mouse, there is no acceptance of the choice; now you have to use the keyboard to scroll down to the observation you want for it to "take".

**Comment by hohonuuli** [comment] 2018-08-09 23:28
This is a duplicate of #30.  The mouse click issue is a known bug in JavaFX. Closing this issue as the details are captured in the duplicate.

**Closed by hohonuuli** 2018-08-09 23:28 UTC
